---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'BlueXP 디지털 지갑을 사용하면 NetApp(BYOL), BlueXP 마켓플레이스 가입 및 NetApp Keystone에서 구입한 BlueXP 라이센스를 관리 및 모니터링할 수 있습니다.' 
---
= BlueXP 디지털 지갑에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  디지털 지갑을 사용하면 BYOL(NetApp), BlueXP  데이터 서비스 마켓플레이스 구독(NetApp Cloud Volumes ONTAP 포함), NetApp Keystone에서 구매한 BlueXP  라이센스를 관리하고 모니터링할 수 있습니다.



== 디지털 지갑에서 라이선스 및 구독이 표시되는 방식

구독에 사용된 BlueXP  계정이 NetApp 지원 사이트 계정인 경우 라이선스 및 구독 모두 자동으로 디지털 지갑에 표시됩니다. NetApp 지원 사이트(NSS) 계정과 연결되지 않은 BlueXP  계정을 사용한 경우 라이선스를 수동으로 추가 및 업데이트해야 하며 사용 현황, 용량 및 기타 세부 정보가 변경되지 않습니다.


NOTE: 디지털 지갑에서 구독 정보를 보려면 커넥터를 배포해야 합니다. Cloud Volumes ONTAP에 대한 노드 라이센스를 보려면 커넥터도 필요합니다.

그 동안 BlueXP는 NetApp의 라이센스 서비스에 대해 자동으로 쿼리하여 NetApp Support 사이트 계정과 연결된 라이센스에 대한 자세한 정보를 확인합니다. 오류가 없으면 BlueXP는 자동으로 디지털 지갑에 라이센스를 추가합니다.

BlueXP 에서 라이선스를 추가할 수 없는 경우 직접 디지털 지갑에 라이선스를 추가해야 합니다. 예를 들어 BlueXP  사용자 계정이 NetApp 지원 사이트 계정과 연결되어 있지 않은 경우 라이선스를 직접 추가해야 합니다.

NetApp 영업 담당자로부터 라이선스를 구입하면 NetApp에서 일련 번호와 추가 라이선스 세부 정보가 포함된 전자 메일을 보냅니다. 디지털 지갑에서 각 라이센스를 추가하거나 업데이트하려면 해당 일련 번호가 필요합니다.

https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-nss-accounts.html["NetApp 지원 사이트 계정을 BlueXP  사용자 자격 증명에 추가하는 방법에 대해 알아봅니다"^]..



== 지원되는 서비스

BlueXP  디지털 지갑을 사용하면 다음 서비스에 대한 라이선스 및 구독을 관리할 수 있습니다.

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["백업 및 복구"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["재해 복구"^] (BYOL만 해당)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["랜섬웨어 보호"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["온프레미스 ONTAP 클러스터"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["계층화"^]

