---
settings:
  name: BlueXP digital wallet
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP 디지털 지갑 문서
    url: "/index.html"
  - title: 릴리스 정보
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
  - title: 시작하십시오
    entries:
    - title: BlueXP 디지털 지갑에 대해 알아보십시오
      url: "/concept-digital-wallet.html"
  - title: BlueXP 디지털 지갑을 사용합니다
    entries:
    - title: Cloud Volumes ONTAP에 대한 라이센스를 관리합니다
      entries:
      - title: 용량 기반 라이센스
        url: "/task-manage-capacity-licenses.html"
      - title: 노드 기반 라이센스
        url: "/task-manage-node-based-licenses.html"
    - title: BlueXP 데이터 서비스의 라이센스를 관리합니다
      url: "/task-manage-data-services-licenses.html"
    - title: PAYGO 구독 및 계약 관리
      url: "/task-manage-subscriptions.html"
    - title: Keystone 가입 관리
      url: "/task-manage-keystone.html"
    - title: 온프레미스 ONTAP 클러스터에 대한 라이센스를 관리합니다
      url: "/task-manage-on-prem-clusters.html"
  - title: 지식 및 지원
    entries:
    - title: 지원을 위해 등록하십시오
      url: "/task-support-registration.html"
    - title: 도움을 받으십시오
      url: "/task-get-help.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
